spring:
  application:
    name: api

  graphql:
    graphiql:
      enabled: true
  mongodb:
    uri: mongodb://root:password@localhost:27016/appdb?authSource=admin
  data:
    redis:
      port: 6379
      timeout: 60000
      host: localhost